<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class AdditionalItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Additional items untuk test pagination
        $additionalItems = [
            [
                'name' => 'Genteng Beton',
                'sku' => 'GEN-001',
                'stock' => 500,
                'unit' => 'buah',
                'category' => 'Material',
                'min_stock' => 100,
                'description' => 'Genteng beton untuk atap',
                'price' => 8500,
                'supplier' => 'CV. Genteng Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Kawat Bendrat',
                'sku' => 'KAW-001',
                'stock' => 50,
                'unit' => 'kg',
                'category' => 'Material',
                'min_stock' => 20,
                'description' => 'Kawat bendrat untuk konstruksi',
                'price' => 25000,
                'supplier' => 'PT. Kawat Indonesia',
                'is_active' => true,
            ],
            [
                'name' => 'Triplek 9mm',
                'sku' => 'TRI-009',
                'stock' => 75,
                'unit' => 'lembar',
                'category' => 'Kayu',
                'min_stock' => 25,
                'description' => 'Triplek tebal 9mm ukuran 122x244 cm',
                'price' => 145000,
                'supplier' => 'PT. Kayu Lapis',
                'is_active' => true,
            ],
            [
                'name' => 'Lem Kayu',
                'sku' => 'LEM-001',
                'stock' => 30,
                'unit' => 'botol',
                'category' => 'Kimia',
                'min_stock' => 10,
                'description' => 'Lem kayu untuk furniture',
                'price' => 35000,
                'supplier' => 'CV. Kimia Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Paku 5cm',
                'sku' => 'PAK-005',
                'stock' => 100,
                'unit' => 'kg',
                'category' => 'Hardware',
                'min_stock' => 25,
                'description' => 'Paku besi ukuran 5cm',
                'price' => 18000,
                'supplier' => 'PT. Hardware Indo',
                'is_active' => true,
            ],
            [
                'name' => 'Sekrup 4x40',
                'sku' => 'SEK-440',
                'stock' => 200,
                'unit' => 'dus',
                'category' => 'Hardware',
                'min_stock' => 50,
                'description' => 'Sekrup besi 4x40mm',
                'price' => 45000,
                'supplier' => 'PT. Hardware Indo',
                'is_active' => true,
            ],
            [
                'name' => 'Cat Besi Hitam',
                'sku' => 'CAT-002',
                'stock' => 40,
                'unit' => 'kaleng',
                'category' => 'Cat',
                'min_stock' => 15,
                'description' => 'Cat besi warna hitam',
                'price' => 85000,
                'supplier' => 'PT. Propan Raya',
                'is_active' => true,
            ],
            [
                'name' => 'Kuas Cat 3"',
                'sku' => 'KUA-003',
                'stock' => 25,
                'unit' => 'buah',
                'category' => 'Alat',
                'min_stock' => 10,
                'description' => 'Kuas cat ukuran 3 inch',
                'price' => 15000,
                'supplier' => 'CV. Alat Bangunan',
                'is_active' => true,
            ],
            [
                'name' => 'Thinner',
                'sku' => 'THI-001',
                'stock' => 60,
                'unit' => 'liter',
                'category' => 'Kimia',
                'min_stock' => 20,
                'description' => 'Thinner untuk pengencer cat',
                'price' => 28000,
                'supplier' => 'CV. Kimia Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Amplas Kayu',
                'sku' => 'AMP-001',
                'stock' => 80,
                'unit' => 'lembar',
                'category' => 'Alat',
                'min_stock' => 30,
                'description' => 'Amplas untuk kayu berbagai ukuran',
                'price' => 5000,
                'supplier' => 'CV. Alat Bangunan',
                'is_active' => true,
            ],
            [
                'name' => 'Bata Merah',
                'sku' => 'BAT-001',
                'stock' => 1000,
                'unit' => 'buah',
                'category' => 'Material',
                'min_stock' => 200,
                'description' => 'Bata merah untuk dinding',
                'price' => 1200,
                'supplier' => 'CV. Bata Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Seng Gelombang',
                'sku' => 'SEN-001',
                'stock' => 150,
                'unit' => 'lembar',
                'category' => 'Material',
                'min_stock' => 50,
                'description' => 'Seng gelombang untuk atap',
                'price' => 95000,
                'supplier' => 'PT. Seng Indonesia',
                'is_active' => true,
            ],
            [
                'name' => 'Kaca 5mm',
                'sku' => 'KAC-005',
                'stock' => 20,
                'unit' => 'lembar',
                'category' => 'Kaca',
                'min_stock' => 5,
                'description' => 'Kaca bening tebal 5mm',
                'price' => 125000,
                'supplier' => 'PT. Kaca Indah',
                'is_active' => true,
            ],
            [
                'name' => 'Lem Keramik',
                'sku' => 'LEM-002',
                'stock' => 45,
                'unit' => 'sak',
                'category' => 'Kimia',
                'min_stock' => 15,
                'description' => 'Lem untuk pemasangan keramik',
                'price' => 55000,
                'supplier' => 'CV. Kimia Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Nat Keramik Putih',
                'sku' => 'NAT-001',
                'stock' => 35,
                'unit' => 'kg',
                'category' => 'Kimia',
                'min_stock' => 10,
                'description' => 'Nat keramik warna putih',
                'price' => 25000,
                'supplier' => 'CV. Kimia Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Waterproofing',
                'sku' => 'WAT-001',
                'stock' => 25,
                'unit' => 'galon',
                'category' => 'Kimia',
                'min_stock' => 8,
                'description' => 'Waterproofing untuk anti bocor',
                'price' => 185000,
                'supplier' => 'PT. Waterproof Indo',
                'is_active' => true,
            ],
            [
                'name' => 'Pipa Galvanis 1"',
                'sku' => 'PIP-001',
                'stock' => 60,
                'unit' => 'batang',
                'category' => 'Pipa',
                'min_stock' => 20,
                'description' => 'Pipa galvanis diameter 1 inch',
                'price' => 125000,
                'supplier' => 'PT. Pipa Jaya',
                'is_active' => true,
            ],
            [
                'name' => 'Elbow PVC 4"',
                'sku' => 'ELB-004',
                'stock' => 40,
                'unit' => 'buah',
                'category' => 'Pipa',
                'min_stock' => 15,
                'description' => 'Elbow PVC diameter 4 inch',
                'price' => 35000,
                'supplier' => 'PT. Rucika',
                'is_active' => true,
            ],
            [
                'name' => 'Kran Air',
                'sku' => 'KRA-001',
                'stock' => 30,
                'unit' => 'buah',
                'category' => 'Sanitair',
                'min_stock' => 10,
                'description' => 'Kran air untuk wastafel',
                'price' => 85000,
                'supplier' => 'PT. Sanitair Indo',
                'is_active' => true,
            ],
            [
                'name' => 'Closet Duduk',
                'sku' => 'CLO-001',
                'stock' => 8,
                'unit' => 'set',
                'category' => 'Sanitair',
                'min_stock' => 3,
                'description' => 'Closet duduk lengkap dengan tangki',
                'price' => 1250000,
                'supplier' => 'PT. Sanitair Indo',
                'is_active' => true,
            ],
        ];

        foreach ($additionalItems as $item) {
            Item::create($item);
        }
    }
}